"""Add foreign key from sales to products

Revision ID: 7ee91f0419a0
Revises: b6b34b3570cf
Create Date: 2025-09-15 16:03:20.089082

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7ee91f0419a0'
down_revision: Union[str, None] = 'b6b34b3570cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sales', 'product_id',
               existing_type=sa.VARCHAR(),
               type_=sa.Integer(),
               existing_nullable=False,
               postgresql_using='product_id::integer') # <-- ADD THIS LINE

    # This part is for creating the relationship in the database
    op.create_foreign_key(
        'fk_sales_product_id', # A name for the constraint
        'sales', 'products', 
        ['product_id'], ['id']
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sales', type_='foreignkey')
    op.create_index(op.f('ix_sales_product_id'), 'sales', ['product_id'], unique=False)
    op.alter_column('sales', 'product_id',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    # ### end Alembic commands ###
